package kim.jeonghyeon.simplearchitecture.plugin.util

fun getApiImplementationName(interfaceName: String) = interfaceName + "Impl"

const val GENERATED_FILE_COMMENT = "GENERATED by Simple Api Plugin"
const val API_CREATION_FUNCTION_PACKAGE_NAME = "kim.jeonghyeon.generated.net"
const val API_CREATION_FUNCTION_FILE_NAME = "HttpClientEx"