# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'kotlinIOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for kotlinIOS
  pod 'sample_base', :path => '../sample-base'

  target 'kotlinIOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'kotlinIOSUITests' do
    # Pods for testing
  end

end
